'use client';

import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {getSupportedLanguages,translateMessagesCached,type SupportedLanguage} from '@safelytold/ui/api';
import {useI18n,useToast} from '@safelytold/ui/context';
import en from '../messages/en.json';

const STATIC=['en','af','zu'];
const FALLBACK:SupportedLanguage[]=[{code:'en',name:'English'},{code:'af',name:'Afrikaans'},{code:'zu',name:'isiZulu'},{code:'xh',name:'isiXhosa'},{code:'st',name:'Sesotho'},{code:'tn',name:'Setswana'},{code:'fr',name:'French'},{code:'pt',name:'Portuguese'},{code:'sw',name:'Swahili'},{code:'ar',name:'Arabic'}];
const EXCLUDED='td,.mono,.chat,pre,code,[data-no-translate],[contenteditable="true"]';
const original=new WeakMap<Text,string>();
const translated=new WeakMap<Text,string>();
const originalAttributes=new WeakMap<Element,Record<string,string>>();
const keyFor=(text:string)=>`staff_auto_${Array.from(text).reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619)>>>0,2166136261).toString(16)}`;
function eligible(node:Text){const p=node.parentElement;const value=node.nodeValue?.trim()??'';return Boolean(p&&value.length>1&&!p.closest(EXCLUDED)&&!/^[-+]?\d[\d\s.,:%/]*$/.test(value)&&!/(https?:\/\/|@|[0-9a-f]{8}-[0-9a-f-]{27}|^[0-9a-f]{32,}$)/i.test(value));}
function collect(root:HTMLElement){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];let n:Node|null;while((n=walker.nextNode()))if(eligible(n as Text))nodes.push(n as Text);return nodes;}

export function StaffLanguage(){const {locale,setLocale,registerDictionary,t}=useI18n();const {push}=useToast();const [languages,setLanguages]=useState(FALLBACK);const [busy,setBusy]=useState(false);const [other,setOther]=useState(false);const [custom,setCustom]=useState('');
 useEffect(()=>{getSupportedLanguages().then(x=>x.languages.length&&setLanguages(x.languages)).catch(()=>{})},[]);
 const apply=useCallback(async(target:string)=>{const root=document.querySelector<HTMLElement>('.staff-layout');if(!root)return;const nodes=collect(root);const attrs=[...root.querySelectorAll<HTMLElement>('[placeholder],[aria-label],[title]')].filter(x=>!x.closest(EXCLUDED));if(target==='en'){nodes.forEach(n=>{const source=original.get(n);if(source)n.nodeValue=n.nodeValue?.replace(n.nodeValue.trim(),source)??source});attrs.forEach(el=>{const values=originalAttributes.get(el);if(values)Object.entries(values).forEach(([k,v])=>el.setAttribute(k,v))});setLocale('en');document.documentElement.lang='en';return}setBusy(true);try{const source:Record<string,string>={...(en as Record<string,string>)};for(const n of nodes){const text=original.get(n)??n.nodeValue!.trim();original.set(n,text);source[keyFor(text)]=text}for(const el of attrs){const saved=originalAttributes.get(el)??{};for(const attr of ['placeholder','aria-label','title']){const value=saved[attr]??el.getAttribute(attr);if(value){saved[attr]=value;source[keyFor(value)]=value}}originalAttributes.set(el,saved)}const values=await translateMessagesCached(target,source);registerDictionary(target,values);for(const n of nodes){const text=original.get(n)!;const value=values[keyFor(text)];if(value&&value!==translated.get(n)){n.nodeValue=n.nodeValue!.replace(n.nodeValue!.trim(),value);translated.set(n,value)}}for(const el of attrs){for(const [attr,text] of Object.entries(originalAttributes.get(el)??{})){const value=values[keyFor(text)];if(value)el.setAttribute(attr,value)}}setLocale(target);document.documentElement.lang=target}catch(e){push(e instanceof Error?e.message:t('lang_failed'),'warn')}finally{setBusy(false)}},[push,registerDictionary,setLocale,t]);
 useEffect(()=>{if(locale!=='en')void apply(locale)},[]);
 useEffect(()=>{const root=document.querySelector<HTMLElement>('.staff-layout');if(!root)return;const observer=new MutationObserver(()=>{if(locale!=='en'&&!busy)void apply(locale)});observer.observe(root,{childList:true,subtree:true});return()=>observer.disconnect()},[locale,busy,apply]);
 function change(value:string){if(value==='__other'){setOther(true);return}setOther(false);void apply(value)}function submit(e:FormEvent){e.preventDefault();const code=custom.toLowerCase().replace(/[^a-z\s-]/g,'').replace(/\s+/g,'-').slice(0,24);if(code)void apply(code)}const options=languages.some(x=>x.code===locale)?languages:[...languages,{code:locale,name:locale}];
 return <div className="row" style={{gap:6}} data-no-translate><label className="sr-only" htmlFor="staff-locale">{t('lang_label')}</label><select id="staff-locale" className="select" style={{width:'auto',padding:'4px 8px',fontSize:'.82rem'}} value={locale} disabled={busy} onChange={e=>change(e.target.value)}>{options.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}<option value="__other">{t('lang_other')}</option></select>{busy&&<span className="muted">{t('lang_translating')}</span>}{other&&<form onSubmit={submit} className="row"><input className="input" value={custom} onChange={e=>setCustom(e.target.value)} placeholder={t('lang_placeholder')}/><button className="btn btn-primary btn-sm" disabled={busy}>{t('lang_apply')}</button></form>}</div>}
