'use client';
import {useEffect,useState} from 'react';
import {Alert,Badge,Button,DataTable,EmptyState,Field,Input,PageHeader,Panel,Select} from '@safelytold/ui/components';
import {useSession,useToast} from '@safelytold/ui/context';
import {createAccessGrant,createStaffIdentity,listAccessGrants,listStaffIdentities,revokeAccessGrant} from '@safelytold/ui/api';
import {staffRoleLabel} from '../../lib/staff';
const ROLES=['case_manager','investigator','reviewer','decision_maker','privacy_officer','protection_officer','support_coordinator','auditor'];
export default function IdentityPage(){
 const {session}=useSession();const {push}=useToast();const [staff,setStaff]=useState<any[]>([]);const [grants,setGrants]=useState<any[]>([]);const [subject,setSubject]=useState('');const [role,setRole]=useState(ROLES[0]);const [resource,setResource]=useState('');const [approvers,setApprovers]=useState('');const allowed=session.roles.some(r=>['tenant_admin','platform_super_admin'].includes(r));
 async function load(){if(!allowed)return;try{const [s,g]=await Promise.all([listStaffIdentities(session),listAccessGrants(session)]);setStaff(s);setGrants(g)}catch(e){push(e instanceof Error?e.message:'Could not load access data','danger')}}
 useEffect(()=>{void load()},[session.accessToken]);
 async function addStaff(){try{await createStaffIdentity({external_subject:subject,roles:[role],organisational_unit_ids:[]},session);setSubject('');await load();push('Staff identity registered','ok')}catch(e){push(e instanceof Error?e.message:'Registration failed','danger')}}
 async function grant(){try{const now=new Date();const until=new Date(now.getTime()+30*86400000);await createAccessGrant({subject_id:subject,resource_id:resource,actions:['read'],purpose:session.purpose,approved_by:approvers.split(',').map(x=>x.trim()).filter(Boolean),valid_from:now.toISOString(),valid_until:until.toISOString()},session);await load();push('Time-bound grant created','ok')}catch(e){push(e instanceof Error?e.message:'Grant failed','danger')}}
 if(!allowed)return <main className="shell"><PageHeader eyebrow="Access control" title="Identity & access" subtitle="Keycloak-backed tenant identities and scoped grants."/><Alert tone="danger" title="Tenant administrator required">Your verified Keycloak roles do not permit identity administration.</Alert></main>;
 return <main className="shell"><PageHeader eyebrow="Access control" title="Identity & access" subtitle="Organisation-scoped identities and dual-approved, time-bound resource grants."/><div className="split"><Panel title="Register staff identity"><Field label="Identity provider reference" required><Input value={subject} onChange={e=>setSubject(e.target.value)}/></Field><Field label="Role"><Select value={role} onChange={e=>setRole(e.target.value)}>{ROLES.map(r=><option key={r} value={r}>{staffRoleLabel(r)}</option>)}</Select></Field><Button onClick={addStaff}>Register</Button></Panel><Panel title="Create scoped grant"><Field label="Staff identity" required><Input value={subject} onChange={e=>setSubject(e.target.value)}/></Field><Field label="Resource reference" required><Input value={resource} onChange={e=>setResource(e.target.value)}/></Field><Field label="Two approvers" hint="Comma separated; requester cannot approve their own grant"><Input value={approvers} onChange={e=>setApprovers(e.target.value)}/></Field><Button onClick={grant}>Create 30-day read grant</Button></Panel></div><Panel title="Organisation staff" padded={false}><DataTable keyField="id" empty={<EmptyState title="No staff identities" description="Register a staff identity above."/>} columns={[{key:'external_subject',label:'Identity reference',render:r=><span className="mono">{r.external_subject}</span>},{key:'roles',label:'Roles',render:r=><Badge>{r.roles.map((value:string)=>staffRoleLabel(value)).join(', ')}</Badge>},{key:'status',label:'Status',render:r=>r.status}]} rows={staff}/></Panel><Panel title="Access grants" padded={false}><DataTable keyField="id" empty={<EmptyState title="No grants" description="Scoped grants appear here."/>} columns={[{key:'subject_id',label:'Staff identity',render:r=>r.subject_id},{key:'resource_id',label:'Resource',render:r=><span className="mono">{r.resource_id}</span>},{key:'actions',label:'Permissions',render:r=>r.actions.join(', ')},{key:'status',label:'Status',render:r=>r.status},{key:'revoke',label:'',render:r=><Button size="sm" variant="danger" onClick={async()=>{await revokeAccessGrant(r.id,session);await load()}}>Revoke</Button>}]} rows={grants}/></Panel></main>
}
