'use client';
import {useEffect,useState} from 'react';
import {Alert,Badge,Button,DataTable,EmptyState,Field,Input,PageHeader,Panel,Select,StatusPill} from '@safelytold/ui/components';
import {useSession,useToast} from '@safelytold/ui/context';
import {createTenant,isSuperuser,listTenants,type TenantView} from '../../lib/admin';
export default function AdminPage(){
 const {session}=useSession();const {push}=useToast();const [rows,setRows]=useState<TenantView[]>([]);const [name,setName]=useState('');const [slug,setSlug]=useState('');const [region,setRegion]=useState('af-south-1');const allowed=isSuperuser(session);
 async function load(){if(!allowed)return;try{setRows(await listTenants(session))}catch(e){push(e instanceof Error?e.message:'Could not load tenants','danger')}}
 useEffect(()=>{void load()},[session.accessToken]);
 async function create(){try{await createTenant({display_name:name,slug,home_region:region},session);setName('');setSlug('');await load()}catch(e){push(e instanceof Error?e.message:'Tenant creation failed','danger')}}
 return <main className="shell"><PageHeader eyebrow="Administration" title="Organisation administration" subtitle="Platform administration does not grant access to organisation cases."/>{!allowed?<Alert tone="danger" title="Platform administrator required">A verified platform administrator account and approved email address are required.</Alert>:<><Alert tone="info" title="Separation of duties">Organisation setup is isolated from case assignments and protected-identity approval.</Alert><div className="split"><Panel title="Onboard organisation"><Field label="Organisation"><Input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Short name"><Input value={slug} onChange={e=>setSlug(e.target.value)}/></Field><Field label="Data region"><Select value={region} onChange={e=>setRegion(e.target.value)}>{['af-south-1','eu-west-1','us-east-1'].map(x=><option key={x}>{x}</option>)}</Select></Field><Button onClick={create}>Create organisation</Button></Panel><Panel title="Administrative controls"><ul><li>Staff identities and grants are managed in Identity & access.</li><li>Provider channel coverage is managed in Operations.</li><li>Case access requires a separate assignment and purpose.</li></ul></Panel></div><Panel title="Organisations" padded={false}><DataTable keyField="id" empty={<EmptyState title="No organisations" description="Onboard an organisation above."/>} columns={[{key:'display_name',label:'Organisation',render:r=><strong>{r.display_name}</strong>},{key:'slug',label:'Short name',render:r=><span className="mono">{r.slug}</span>},{key:'home_region',label:'Region',render:r=><Badge>{r.home_region}</Badge>},{key:'status',label:'Status',render:r=><StatusPill status={r.status}/> }]} rows={rows}/></Panel></>}</main>
}
